project:
  type: website
  output-dir: _site

website:
  page-navigation: true
  title: "EarthData Cloud Cookbook"
  site-url: https://nasa-openscapes.github.io/earthdata-cloud-cookbook
  
  repo-url: https://github.com/nasa-openscapes/earthdata-cloud-cookbook
  repo-actions: [edit, issue]

  page-footer: "NASA Openscapes Team (2021). Earthdata Cloud Cookbook (Version v0.0.1)."
  
  sidebar:
    logo: images/nasa-openscapes.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nasa-openscapes.github.io
        text: "NASA-Openscapes website"
      - icon: github
        href: https://github.com/nasa-openscapes/earthdata-cloud-cookbook
        text: "Earthdata Cloud Cookbook repo"
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: index.qmd
      - our-cookbook.qmd  
      - cheatsheet.qmd      
      - section: how-tos/index.qmd
        contents: 
          - section: "Find data"
            contents:
              - find-data/index.md
              - text: "Earthdata Search"        
                href: how-tos/01_Earthdata_Search.md
          - text: "Authentication"
            href: how-tos/authentication.md
          - section: "Transform"
            contents:
              - transform/index.md
          - section: "Access - Cloud Workflow"
            contents:
              - how-tos/Earthdata_Cloud__Single_File__HTTPS_Access_COG_Example.ipynb
              - how-tos/Earthdata_Cloud__Single_File__Direct_S3_Access_COG_Example.ipynb
              - how-tos/Earthdata_Cloud__Single_File__Direct_S3_Access_NetCDF4_Example.ipynb
              - how-tos/Multi-File_Direct_S3_Access_NetCDF_Example.ipynb
          - how-tos/download.qmd
          - how-tos/tech-setup.qmd
      - section: tutorials/index.qmd
        contents:
          - tutorials/04_On-Prem_Cloud.ipynb
      # - section: "Getting Started"
      #   contents:
       #   - get-started/index.md
         # - get-started/earthdata-login.qmd
         # - get-started/api-primer.qmd
      - section: in-development/index.qmd
        contents:
          - href: examples/earthdata-access-demo.qmd
            text: "NASA Earthdata Access Demo"
          - href: examples/NSIDC/ICESat2-CMR-OnPrem-vs-Cloud.ipynb
            text: "Search & Download NSIDC Cloud"
          - href: examples/NSIDC/ICESat2-CMR-AWS-S3.ipynb
            text: "Access NSIDC Cloud w/ CMR"          
          - href: examples/Transform-workflow.ipynb
            text: "Direct Access & Harmony Workflow"
          - href: examples/USGS_Landsat/Landsat_C2_Search_Access.ipynb
            text: "Search & Access USGS Landsat Cloud"  
          - examples/ORNL/Data_Access__Direct_S3_Access__ORNL_DAYMET.ipynb
          - external/cof-zarr-reformat.ipynb
          - external/zarr-eosdis-store.ipynb
          - section: examples/index.qmd
            contents: 
              #- examples/GESDISC/GESDISC_MERRA2_tavg1_2d_flx_Nx__Kerchunk.ipynb
              - href: examples/LPDAAC/LPDAAC_ECOSTRESS_LSTE__Kerchunk.ipynb
                text: "LPDAAC kerchunk example"
              - href: examples/PODAAC/PODAAC_ECCO_SSH__Kerchunk.ipynb
                text: "PODAAC ECCO kerchunk example"
      - section: contributing/index.qmd
        contents: 
          - contributing/onboarding.qmd
          - contributing/setup.qmd
          - contributing/workflow.md
          - contributing/resources.md
          - contributing/quarto-website-tutorial.md
      - troubleshooting.md

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto
