project:
  type: site
  output-dir: _site
  
execute:
  ipynb: false
  freeze: true

site:
  title: "EarthData Cloud Cookbook"  
  site-url: https://nasa-openscapes.github.io/earthdata-cloud-cookbook
  repo-url: https://github.com/nasa-openscapes/earthdata-cloud-cookbook
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    logo: nasa-openscapes.png 
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    align: left
    tools:
      - icon: github
        href: https://github.com/nasa-openscapes/earthdata-cloud-cookbook
    contents:
      - text: "Welcome"
        href: index.md  
      - section: get-started/index.md
        contents:
          - get-started/how-to-use.md
          - get-started/api-primer.md
          - get-started/earthdata-login.md
          - section: get-started/authentication.md
            contents:
              - get-started/lpdaac-netrc.ipynb
              - get-started/podaac-ecco-netrc.ipynb
      - section: discovery/index.md
        contents:
          - discovery/Navigate_CMR_STAC.ipynb
          - discovery/earthdata-search-ui.md
          - discovery/cmr-virtual-directories.md
      - section: access/index.md
        contents:
          - access/earthdata-search.md
          - access/opendap-cloud.md
          - access/cof-via-harmony.md
          - access/download-to-local.md
      - section: transformations/index.md
        contents:
          - transformations/harmony-api.md
          - transformations/harmonypy.md
          - transformations/earthdata-search.md
          - transformations/opendap-cloud.md
      - section: examples/index.md
        contents:
          - examples/python-example.qmd
          - examples/r-examples.Rmd
      - section: appendix/index.md
        contents:
          - appendix/about.md
          - appendix/glossary.md
      - section: contributing/index.md
        contents:
          - contributing/setup.md
          - contributing/workflow.md

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
