project:
  type: website
  output-dir: _site

website:
  page-navigation: true
  title: "EarthData Cloud Cookbook"
  site-url: https://nasa-openscapes.github.io/earthdata-cloud-cookbook
  
  repo-url: https://github.com/nasa-openscapes/earthdata-cloud-cookbook
  repo-actions: [edit, issue]

  page-footer: "NASA Openscapes Team (2021). Earthdata Cloud Cookbook (Version v0.0.1)."
  
  sidebar:
    logo: images/nasa-openscapes.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nasa-openscapes.github.io
        text: "NASA-Openscapes website"
      - icon: github
        href: https://github.com/nasa-openscapes/earthdata-cloud-cookbook
        text: "Earthdata Cloud Cookbook repo"
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: index.md
      - cheatsheet.md
      - using-cookbook.md  
      - section: "How To Guides"
        contents: 
          - how-to/search.md
          - how-to/access.md
          - how-to/subset.md
      - section: "Tutorials"
        contents:
          - tutorials/index.md
      # - section: "Getting Started"
      #   contents:
       #   - get-started/index.md
         # - get-started/earthdata-login.qmd
         # - get-started/api-primer.qmd
      - section: "Sandbox"
        contents:
          - href: examples/earthdata-access-demo.qmd
            text: "NASA Earthdata Access Demo"
          - href: examples/NSIDC/ICESat2-CMR-OnPrem-vs-Cloud.ipynb
            text: "Search & Download NSIDC Cloud"
          - href: examples/NSIDC/ICESat2-CMR-AWS-S3.ipynb
            text: "Access NSIDC Cloud w/ CMR"          
          - href: examples/Transform-workflow.ipynb
            text: "Direct Access & Harmony Workflow"
          - href: examples/USGS_Landsat/Landsat_C2_Search_Access.ipynb
            text: "Search & Access USGS Landsat Cloud"  
          - examples/ORNL/Data_Access__Direct_S3_Access__ORNL_DAYMET.ipynb
          - external/cof-zarr-reformat.ipynb
          - external/zarr-eosdis-store.ipynb
      - section: "Contributing"
        contents:
          - contributing/index.md
          - contributing/setup.qmd
          - contributing/workflow.md
          - contributing/resources.md
          - contributing/quarto-website-tutorial.md

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto
