project:
  type: website
  output-dir: _site

execute:
  freeze: true  # never re-execute computational content during project render, needed for .qmd and .rmd since quarto does not render .ipynb by default

website:
  page-navigation: true
  title: "EarthData Cloud Cookbook"
  site-url: https://nasa-openscapes.github.io/earthdata-cloud-cookbook
  
  repo-url: https://github.com/nasa-openscapes/earthdata-cloud-cookbook
  repo-actions: [edit, source, issue]

  page-footer: "NASA Openscapes Team (2021). Earthdata Cloud Cookbook (Version v0.0.1)."
  
  sidebar:
    title: "NASA Earthdata Cloud Cookbook"
    logo: images/nasa-openscapes.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nasa-openscapes.github.io
        text: "NASA-Openscapes website"
      - icon: github
        href: https://github.com/nasa-openscapes/earthdata-cloud-cookbook
        text: "Earthdata Cloud Cookbook repo"
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: index.qmd
      - our-cookbook.qmd  
      - text: "Cheatsheets & Slides" 
        href: cheatsheets.qmd      
      - section: how-tos/index.qmd
        contents: 
          - section: how-tos/find-data/index.md
            contents:
              - text: "How do I find data using Earthdata Search"
                href: how-tos/find-data/earthdata_search.md
              - text: "How do I find data using the command line or a notebook" 
                href: how-tos/find-data/programmatic.qmd                
          - section: how-tos/working-with-data-in-cloud/index.md
            contents:
              - text: "Direct Cloud Access"
                href: how-tos/working-with-data-in-cloud/Direct-Cloud-Access.qmd
              - text: "Access Data behind a EULA" 
                href: how-tos/working-with-data-in-cloud/Access-EULA-Data.qmd
          - section: how-tos/working-locally/index.md
            contents:
              - text: "Download Data"
                href: how-tos/working-locally/download.qmd
          - section: how-tos/subset/index.md
            contents: 
              - text: "How do I download a subset of NetCDF-4?" 
                href: how-tos/subset/subset.md
          - section: "How do I reformat data files?"
            contents:
              - text: "How do I convert a NetCDF file to Zarr"
                href: how-tos/reformat/reformat.md
          - section: how-tos/reproject_and_regrid/index.md
            contents:
              - text: "How do I reproject a data granule using Harmony?"
                href: how-tos/reproject_and_regrid/reproject.md
          - section: "How do I aggregate data?"
            contents:
              - text: "How do I calulate a climatology?"
                href: how-tos/aggregate/aggregate.ipynb
          - section: "How do I plot data?"
            contents:
              - text: "How do I plot a NetCDF variable?"
                href: how-tos/plot/index.md
          - section: "How do I setup an AWS instance?"
            contents:
              - text: "Place holder for AWS setup"
                href: how-tos/tech-setup.qmd
          - how-tos/how_to_guide_parking_lot.md
      - section: tutorials/index.qmd
        contents:
          - href: tutorials/earthaccess-demo.ipynb
            text: "`earthaccess` Python library"
      # - section: "Getting Started"
      #   contents:
       #   - get-started/index.md
         # - get-started/earthdata-login.qmd
         # - get-started/api-primer.qmd
      - section: in-development/index.qmd
        contents:
          - href: examples/NSIDC/ICESat2-CMR-OnPrem-vs-Cloud.ipynb
            text: "Search & Download NSIDC Cloud"
          - href: examples/NSIDC/ICESat2-CMR-AWS-S3.ipynb
            text: "Access NSIDC Cloud w/ CMR"          
          - href: examples/Transform-workflow.ipynb
            text: "Direct Access & Harmony Workflow"
          - href: examples/USGS_Landsat/Landsat_C2_Search_Access.ipynb
            text: "Search & Access USGS Landsat Cloud"  
          - text: "OPeNDAP" 
            href: how-tos/working-with-data-in-cloud/Earthdata_Cloud__Data_Access_OPeNDAP_Example.ipynb
          - examples/ORNL/Data_Access__Direct_S3_Access__ORNL_DAYMET.ipynb
          - external/cof-zarr-reformat.ipynb
          - external/zarr-eosdis-store.ipynb
          - section: examples/index.qmd
            contents: 
              - examples/GESDISC/GESDISC_MERRA2_tavg1_2d_flx_Nx__Kerchunk.ipynb
              - examples/LPDAAC/LPDAAC_ECOSTRESS_LSTE__Kerchunk.ipynb
              - examples/PODAAC/PODAAC_ECCO_SSH__Kerchunk.ipynb
          - href: in-development/matlab.qmd
            text: "Matlab & AWS"
          - href: in-development/CMR-STAC-Search.Rmd
            text: "CMR STAC in R"  
          - href: in-development/earthdata-python-r-handoff.qmd  
      - section: contributing/index.qmd
        contents: 
          - contributing/onboarding.qmd
          - contributing/setup.qmd
          - contributing/workflow.qmd
          - contributing/resources.md
          - contributing/quarto-website-tutorial.md
      - section: appendix/index.md
        contents:
          - appendix/authentication.qmd
      - troubleshooting.md

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto
