project:
  type: site
  output-dir: docs
  
site:
  title: "Cloud for Earth Science"
  author: "NASA Openscapes Community"
  logo: openscapes_hex.png
  repo-url: https://github.com/nasa-openscapes/quartobook-test
  repo-actions: [edit, issue]
  sharing: [twitter]
  page-navigation: true
  sidebar:
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    tools:
      - icon: github
        href: https://github.com/nasa-openscapes/quartobook-test
    contents:
      - text: "Welcome"
        href: index.md  
      - section: get-started/index.md
        contents:
          - get-started/how-to-use.md
          - get-started/api-primer.md
          - get-started/earthdata-login.md
          - section: get-started/authentication.md
            contents:
              - get-started/how-to-use.md
              - get-started/lpdaac-netrc.ipynb
              - get-started/podaac-ecco-netrc.ipynb
      - section: discovery/index.md
        contents:
          - discovery/Navigate_CMR_STAC.ipynb
          - discovery/earthdata-search-ui.md
          - discovery/cmr-virtual-directories.md
      - section: access/index.md
        contents:
          - access/data-access-example.qmd
          - access/earthdata-search.md
          - access/opendap-cloud.md
          - access/cof-via-harmony.md
          - access/download-to-local.md
      - section: transformations/index.md
        contents:
          - transformations/harmony-api.md
          - transformations/harmonypy.md
          - transformations/earthdata-search.md
          - transformations/opendap-cloud.md
      - section: examples/index.md
        contents:
          - examples/python_example.qmd
          - examples/r_example.Rmd
      - section: appendix/index.md
        contents:
          - appendix/about.md
          - appendix/glossary.md
      - section: community-handbook/index.md
        contents:
          - community-handbook/contributing.Rmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
