project:
  type: site
  output-dir: docs
  
execute:
  ipynb: false
  freeze: true

site:
  title: "EarthData Cloud Cookbook"  
  site-url: https://nasa-openscapes.github.io/earthdata-cloud-cookbook
  repo-url: https://github.com/nasa-openscapes/earthdata-cloud-cookbook
  repo-actions: [edit, issue]
  page-navigation: true
  sidebar:
    logo: nasa-openscapes.png 
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    align: left
    tools:
      - icon: github
        href: https://github.com/nasa-openscapes/earthdata-cloud-cookbook
    contents:
      - text: "Welcome"
        href: index.md  
      - section: files/get-started/index.md
        contents:
          - files/get-started/how-to-use.md
          - files/get-started/api-primer.md
          - files/get-started/earthdata-login.md
          - section: "Authentication" # get-started/authentication.md -- potential bug
            contents:
              - files/get-started/lpdaac-netrc.ipynb
              - files/get-started/podaac-ecco-netrc.ipynb
      - section: files/discovery/index.md
        contents:
          - files/discovery/Navigate_CMR_STAC.ipynb
          - files/discovery/earthdata-search-ui.md
          - files/discovery/cmr-virtual-directories.md
      - section: files/access/index.md
        contents:
       #   - files/access/data-access-example.qmd
          - files/access/earthdata-search.md
          - files/access/opendap-cloud.md
          - files/access/cof-via-harmony.md
          - files/access/download-to-local.md
      - section: files/transformations/index.md
        contents:
          - files/transformations/harmony-api.md
          - files/transformations/harmonypy.md
          - files/transformations/earthdata-search.md
          - files/transformations/opendap-cloud.md
      - section: files/examples/index.md
        contents:
          - files/examples/python-example.ipynb
      - section: files/appendix/index.md
        contents:
          - files/appendix/about.md
          - files/appendix/glossary.md
      - section: files/contributing/index.md
        contents:
          - files/contributing/setup.md
          - files/contributing/workflow.md

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
