project:
  type: site
  output-dir: _site

execute:
  freeze: true

site:
  title: "EarthData Cloud Cookbook"
  site-url: https://nasa-openscapes.github.io/earthdata-cloud-cookbook
  repo-url: https://github.com/nasa-openscapes/earthdata-cloud-cookbook
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer: "NASA Openscapes Team (2021). Earthdata Cloud Cookbook (Version v0.0.1)."
  

  navbar: 
    background: light
    right: 
      - sidebar:menu
      - icon: github
        href: https://github.com/nasa-openscapes/earthdata-cloud-cookbook  
  
  sidebar:
    - id: menu
      title: "Menu"
      logo: nasa-openscapes.png
      style: "docked"
      collapse-level: 2
      align: left    
      contents:
        - text: "Welcome"
          href: index.md
        - section: get-started/index.md
          contents:
            - get-started/how-to-use.md
            - get-started/earthdata-login.qmd
            - section: get-started/authentication.md
              contents:
                - get-started/lpdaac-netrc.ipynb
                - get-started/podaac-ecco-netrc.ipynb
            - get-started/api-primer.qmd
        - section: discovery/index.md
          contents:
            - discovery/search-by-shapefile.qmd
            - discovery/Navigate_CMR_STAC.ipynb
            - discovery/earthdata-search-ui.md
            - discovery/cmr-virtual-directories.md
        - section: access/index.md
          contents:
            - access/data-access-example.ipynb
            - access/earthdata-search.md
            - access/opendap-cloud.md
            - section: access/direct-in-region.md
              contents:
                - access/podaac-ecco-data_access-cloud_direct_access_s3.ipynb
            - section: access/cof-via-harmony.md
              contents:
                - external/cof-zarr-reformat.ipynb
            - access/download-to-local.md
        - section: transformations/index.md
          contents:
            - transformations/harmony-api.md
            - transformations/HarmonyPy_intro_tutorial.ipynb
            - transformations/netcdf-to-zarr.md
            - section: transformations/L2-subsetter.md
              contents: 
                - transformations/harmony-subsetting.qmd
            - transformations/earthdata-search.md
            - transformations/opendap-cloud.md
            - external/zarr-eosdis-store.ipynb
        - section: examples/index.md
          contents:
            - examples/NSIDC/ICESat2-CMR-OnPrem-vs-Cloud.ipynb
            - examples/NSIDC/ICESat2-CMR-AWS-S3.ipynb
        - section: appendix/index.md
          contents:
            - transformations/harmonypy.md
        - section: contributing/index.md
          contents:
            - contributing/setup.qmd
            - contributing/workflow.md

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto