project:
  type: site
  output-dir: docs
  
site:
  title: "Cloud for Earth Science"
  author: "NASA Openscapes Community"
  logo: openscapes_hex.png
  repo-url: https://github.com/nasa-openscapes/quartobook-test
  repo-actions: [edit, issue]
  sharing: [twitter]
  page-navigation: true
  sidebar:
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    tools:
      - icon: github
        href: https://github.com/nasa-openscapes/quartobook-test
    contents:
      - text: "Welcome"
        href: index.md  
      - section: "Getting Started"
        contents:
          - getting_started/getting_started.md
          - section: "Authentication Notebooks"
            contents:
              - getting_started/lpdaac-netrc.ipynb
              - getting_started/podaac-ecco-netrc.ipynb
      - section: "NASA Cloud Data Discovery"
        contents:
          - discovery/discovery.md
          - section: "Discover Notebooks"
            contents:
              - discovery/Navigate_CMR_STAC.ipynb
      - section: "Access"
        contents:
          - access/access.md
          - section: "Access Notebooks"
            contents:
              - discovery/Navigate_CMR_STAC.ipynb
      - section: "Further Resources"
        contents:
          - further_resources/glossary.md
          - further_resources/python_example.qmd
          - further_resources/r_example.Rmd
      - section: "Community Handbook"
        contents:
          - community-handbook/community-handbook.md

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
