project:
  type: site
  output-dir: _site
  
site:
  title: "Cloud for Earth Science"
  author: "NASA Openscapes Community"
  logo: docs/images/openscapes-hex.png
  repo-url: https://github.com/nasa-openscapes/quartobook-test
  repo-actions: [edit, issue]
  sharing: [twitter]
  page-navigation: true
  sidebar:
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    tools:
      - icon: github
        href: https://github.com/nasa-openscapes/quartobook-test
    contents:
      - text: "Welcome"
        href: index.md  
      - section: docs/get-started/index.md
        contents:
          - docs/get-started/how-to-use.md
          - docs/get-started/api-primer.md
          - docs/get-started/earthdata-login.md
          - section: "Authentication" # get-started/authentication.md -- potential bug
            contents:
              - docs/get-started/how-to-use.md
              - docs/get-started/lpdaac-netrc.ipynb
              - docs/get-started/podaac-ecco-netrc.ipynb
      - section: docs/discovery/index.md
        contents:
          - docs/discovery/Navigate_CMR_STAC.ipynb
          - docs/discovery/earthdata-search-ui.md
          - docs/discovery/cmr-virtual-directories.md
      - section: docs/access/index.md
        contents:
          - docs/access/data-access-example.qmd
          - docs/access/earthdata-search.md
          - docs/access/opendap-cloud.md
          - docs/access/cof-via-harmony.md
          - docs/access/download-to-local.md
      - section: docs/transformations/index.md
        contents:
          - docs/transformations/harmony-api.md
          - docs/transformations/harmonypy.md
          - docs/transformations/earthdata-search.md
          - docs/transformations/opendap-cloud.md
      - section: docs/examples/index.md
        contents:
          - docs/examples/python_example.qmd
          - docs/examples/r_example.Rmd
      - section: docs/appendix/index.md
        contents:
          - docs/appendix/about.md
          - docs/appendix/glossary.md
      - section: docs/community-handbook/index.md
        contents:
          - docs/community-handbook/contributing.Rmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
