project:
  type: site
  output-dir: docs
  
site:
  title: "Cloud for Earth Science"
  author: "NASA Openscapes Community"
  logo: openscapes_hex.png
  repo-url: https://github.com/nasa-openscapes/quartobook-test
  repo-actions: [edit, issue]
  sharing: [twitter]
  page-navigation: true
  sidebar:
    style: "docked"
    background: light
    search: true
    collapse-level: 2
    tools:
      - icon: github
        href: https://github.com/nasa-openscapes/quartobook-test
    contents:
      - text: "Welcome"
        href: index.md  
      - section: get-started/index.md
        contents:
          - get-started/how-to-use.md
          - get-started/api-primer.md
          - get-started/earthdata-login.md
          - section: "Authentication (TODO as page)"
            contents:
              - get-started/how-to-use.md
              - discovery/Navigate_CMR_STAC.ipynb
              - get-started/lpdaac-netrc.ipynb
              - get-started/podaac-ecco-netrc.ipynb
      - section: discovery/index.md
        contents:
          - discovery/Navigate_CMR_STAC.ipynb
          - discovery/earthdata-search-ui.md
          - discovery/cmr-virtual-directories.md
      - section: access/index.md
        contents:
          - access/data-access-example.qmd
          - section: "Access Notebooks"
            contents:
              - discovery/Navigate_CMR_STAC.ipynb
      - section: "Further Resources"
        contents:
          - further_resources/glossary.md
          - further_resources/python_example.qmd
          - further_resources/r_example.Rmd
      - section: "Community Handbook"
        contents:
          - community-handbook/community-handbook.md

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
