name: nsidc-cloud
channels:
- conda-forge
- nsidc
dependencies:
- python=3.8
- awscli~=1.19
- ipyleaflet~=0.13.5
- xarray~=0.18
- rioxarray~=0.3.1
- netcdf4~=1.5.6
- h5netcdf~=0.11
- h5py~=3.2
- geopandas~=0.9.0
- geojson~=2.5
- matplotlib-base~=3.3.4
- bqplot~=0.12.23
- cartopy~=0.18.0
- joblib~=1.0.1
- requests~=2.25.1
- tqdm~=4.59.0
- dask~=2021.7.2
- dask-labextension~=5.0.1
- jupyterlab=3
- ipympl~=0.6.3
- s3fs~=2021.6
- sidecar~=0.5.0
- fsspec~=2021.6.1
- s3fs~=2021.6.1
- zarr~=2.8
- pip
- pip:
  - pqdm
  - git+https://github.com/nasa/eo-metadata-tools/#egg=eo-metadata-tools-cmr&subdirectory=CMR/python
  # - git+https://github.com/nsidc/python-cmr.git
