name: openscapes
channels:
  - conda-forge
dependencies:
  - python=3.10
  - dask-labextension
  - jupyter-server-proxy
  - jupyter-vscode-proxy
  - jupyter-rsession-proxy
  - ipywidgets
  - jupyter-book
  - jupyterlab>4
  - jupyterlab-myst
  - jupyterhub-singleuser
  - jupyterlab-geojson
  - jupyterlab-favorites
  - jupyterlab-git
  - jupyter-resource-usage
  - jupyterlab-h5web
  - code-server >=3.2
  - pip
