name: Docker Image CI venv
on:
  workflow_dispatch: null
  push:
    paths:
      - '.devcontainer/venv.Dockerfile'
      - '.devcontainer/nasa-requirements.txt'
      - '.github/workflows/docker-image-venv.yml'
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'eeholmes/earthdata-cloud-cookbook'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        if: github.repository == 'eeholmes/earthdata-cloud-cookbook'
        run: |
          docker build .devcontainer -f .devcontainer/venv.Dockerfile  --tag ghcr.io/eeholmes/earthdata-cloud-cookbook/cookbook-venv:latest
      - name: Publish
        if: github.repository == 'eeholmes/earthdata-cloud-cookbook'
        run: |
          docker push ghcr.io/eeholmes/earthdata-cloud-cookbook/cookbook-venv:latest

